from django.contrib import admin
from .models import *

admin.site.register(Aluno)
admin.site.register(ResponsavelEducativo)
admin.site.register(AlunoSaida)
admin.site.register(Vacinacao)
admin.site.register(DespesaFixa)
admin.site.register(DespesasVariavel)
admin.site.register(Salario)
admin.site.register(LinkFiliacao)
admin.site.register(Sala)
admin.site.register(MensalidadeAluno)
admin.site.register(AlunoFinancas)
admin.site.register(AlunoFinacasCalc)
admin.site.register(Funcionario)
admin.site.register(SaudeFinanceiraBalancoGlobal)
admin.site.register(EscaloesRendimento)
admin.site.register(ComparticaoMensalSS)
admin.site.register(ConfigIpss)
admin.site.register(PedidoDeMudanca)
admin.site.register(programa)