# Generated by Django 5.1.5 on 2025-02-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aluno',
            fields=[
                ('aluno_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=250)),
                ('processo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
    ]
