# Generated by Django 5.1.6 on 2025-03-25 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=250)),
                ('archive_flag', models.BooleanField(default=False)),
                ('processo', models.CharField(blank=True, max_length=150, null=True)),
                ('data_admissao', models.DateTimeField()),
                ('data_ultima_renovacao', models.DateTimeField(blank=True, null=True)),
                ('data_nascimento', models.DateTimeField()),
                ('documento', models.CharField(default='', max_length=250)),
                ('numero_documento', models.CharField(default='', max_length=100)),
                ('data_validade', models.DateTimeField()),
                ('niss', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('morada', models.CharField(default='', max_length=150)),
                ('codigo_postal', models.CharField(default='', max_length=150)),
                ('concelho', models.CharField(default='', max_length=150)),
                ('fregesia', models.CharField(blank=True, max_length=150, null=True)),
                ('escolaridade_anterior', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo_admissao', models.CharField(blank=True, max_length=150, null=True)),
                ('cuidados_especias', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='AlunoFinacasCalc',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=255)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('valencia', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'aluno_finacas_calc',
            },
        ),
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('despfix_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(default='', max_length=250)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('fatura', models.IntegerField()),
                ('pagamento', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'despesa_fixa',
            },
        ),
        migrations.CreateModel(
            name='DespesasVariavel',
            fields=[
                ('despvar_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(default='', max_length=250)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('fatura', models.IntegerField()),
                ('pagamento', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'despesas_variavel',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('tipo_documento_identificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento_identificacao', models.CharField(default='', max_length=50)),
                ('data_validade', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('niss', models.IntegerField()),
                ('nif', models.IntegerField()),
                ('morada', models.CharField(default='', max_length=255)),
                ('codigo_postal', models.CharField(default='', max_length=255)),
                ('concelho', models.CharField(blank=True, max_length=255, null=True)),
                ('freguesia_residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_telefonico', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(default='', max_length=255)),
                ('escalao_profissional', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('salario_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('data_pagamento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('subsidio_tipo', models.CharField(default='', max_length=20)),
                ('subsidio_valor', models.FloatField()),
            ],
            options={
                'db_table': 'salario',
            },
        ),
        migrations.CreateModel(
            name='AlunoFinancas',
            fields=[
                ('af_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano_letivo', models.CharField(default='', max_length=255)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('agregado', models.IntegerField()),
                ('rendim_líquido', models.IntegerField()),
                ('despesa_anual', models.IntegerField()),
                ('irs', models.CharField(default='', max_length=255)),
                ('tax_soc', models.CharField(default='', max_length=255)),
                ('tax_impos', models.CharField(blank=True, max_length=255, null=True)),
                ('renda', models.IntegerField(blank=True, null=True)),
                ('med_transp', models.CharField(blank=True, max_length=255, null=True)),
                ('medicacao', models.CharField(blank=True, max_length=255, null=True)),
                ('outros', models.CharField(blank=True, max_length=255, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'aluno_financas',
            },
        ),
        migrations.CreateModel(
            name='AlunoSaida',
            fields=[
                ('saida_id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('autorizacao_sair', models.CharField(blank=True, max_length=250, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
                ('valencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.alunofinacascalc')),
            ],
            options={
                'db_table': 'aluno_saida',
            },
        ),
        migrations.AddField(
            model_name='alunofinacascalc',
            name='func_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario'),
        ),
        migrations.CreateModel(
            name='MensalidadeAluno',
            fields=[
                ('ma_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField(default=django.utils.timezone.now)),
                ('periodo_fim', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('mensalidade_calc', models.IntegerField(blank=True, null=True)),
                ('mensalidade_retific', models.IntegerField(blank=True, null=True)),
                ('mensalidade_paga', models.IntegerField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modo_pagamento', models.CharField(blank=True, max_length=255, null=True)),
                ('acordo', models.CharField(blank=True, max_length=255, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.alunofinancas')),
            ],
            options={
                'db_table': 'mensalidade_aluno',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelEducativo',
            fields=[
                ('responsavel_educativo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=250)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.CharField(default='', max_length=150)),
                ('numero_documento', models.IntegerField()),
                ('data_validade', models.DateField(default=django.utils.timezone.now)),
                ('niss', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('morada', models.CharField(default='', max_length=250)),
                ('codigo_postal', models.CharField(default='', max_length=100)),
                ('concelho', models.CharField(default='', max_length=150)),
                ('fregesia', models.CharField(default='', max_length=150)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('profissao', models.CharField(blank=True, max_length=150, null=True)),
                ('morada_emprego', models.CharField(blank=True, max_length=150, null=True)),
                ('horario_trabalho', models.TimeField(blank=True, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'responsavel_educativo',
            },
        ),
        migrations.CreateModel(
            name='LinkFiliacao',
            fields=[
                ('filiacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='', max_length=100)),
                ('encarr_educacao', models.BooleanField(blank=True, default=False, null=True)),
                ('aluno_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
                ('re_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo')),
            ],
            options={
                'db_table': 'link_filiacao',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('sala_nome', models.CharField(default='', max_length=255)),
                ('sala_local', models.CharField(blank=True, max_length=255, null=True)),
                ('sala_valencia', models.CharField(default='', max_length=255)),
                ('func_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='sala_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.sala'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.salario'),
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('vac_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacina_name', models.CharField(default='', max_length=250)),
                ('data_vacina', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('plano_vacina', models.BooleanField(blank=True, default=False, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'vacinacao',
            },
        ),
    ]
