# Generated by Django 5.1.6 on 2025-03-12 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('aluno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=250)),
                ('processo', models.CharField(blank=True, max_length=150, null=True)),
                ('data_admissao', models.DateField(default=django.utils.timezone.now)),
                ('data_ultima_renovacao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.CharField(default='', max_length=250)),
                ('numero_documento', models.CharField(default='', max_length=100)),
                ('data_validade', models.DateField(default=django.utils.timezone.now)),
                ('niss', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('morada', models.CharField(default='', max_length=150)),
                ('codigo_postal', models.CharField(default='', max_length=150)),
                ('concelho', models.CharField(default='', max_length=150)),
                ('fregesia', models.CharField(blank=True, max_length=150, null=True)),
                ('escolaridade_anterior', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo_admissao', models.CharField(blank=True, max_length=150, null=True)),
                ('cuidados_especias', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('despesa_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(default='', max_length=250)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(default='', max_length=250)),
                ('data', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
        migrations.CreateModel(
            name='AlunoSaida',
            fields=[
                ('aluno_saida_id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('autorizacao_sair', models.CharField(blank=True, max_length=250, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'aluno_saida',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelEducativo',
            fields=[
                ('responsavel_educativo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=250)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.CharField(default='', max_length=150)),
                ('numero_documento', models.IntegerField()),
                ('data_validade', models.DateField(default=django.utils.timezone.now)),
                ('niss', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('morada', models.CharField(default='', max_length=250)),
                ('codigo_postal', models.CharField(default='', max_length=100)),
                ('concelho', models.CharField(default='', max_length=150)),
                ('fregesia', models.CharField(default='', max_length=150)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('profissao', models.CharField(blank=True, max_length=150, null=True)),
                ('morada_emprego', models.CharField(blank=True, max_length=150, null=True)),
                ('horario_trabalho', models.TimeField(blank=True, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'responsavel_educativo',
            },
        ),
        migrations.CreateModel(
            name='Filiacao',
            fields=[
                ('filiacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('filiacao_responsavel', models.CharField(default='', max_length=100)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
                ('responsavel_educativo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo')),
            ],
            options={
                'db_table': 'filiacao',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('salario_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('data_pagamento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('subsidio_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('subsidio_valor', models.FloatField(blank=True, null=True)),
                ('responsavel_educativo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo')),
            ],
            options={
                'db_table': 'salario',
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('vacinacao_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacina_name', models.CharField(default='', max_length=250)),
                ('data_vacina', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('plano_vacina', models.BooleanField(blank=True, default=False, null=True)),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'vacinacao',
            },
        ),
    ]
