# Generated by Django 5.1.6 on 2025-03-26 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='sala_id',
            field=models.ForeignKey(db_column='sala_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.sala'),
        ),
        migrations.AlterField(
            model_name='alunofinacascalc',
            name='func_id',
            field=models.ForeignKey(blank=True, db_column='func_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario'),
        ),
        migrations.AlterField(
            model_name='alunofinancas',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='alunosaida',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='alunosaida',
            name='valencia',
            field=models.ForeignKey(db_column='valencia', on_delete=django.db.models.deletion.CASCADE, to='data_hub.alunofinacascalc'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.ForeignKey(blank=True, db_column='salario', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.salario'),
        ),
        migrations.AlterField(
            model_name='mensalidadealuno',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='mensalidadealuno',
            name='ano_letivo',
            field=models.ForeignKey(db_column='ano_letivo', on_delete=django.db.models.deletion.CASCADE, to='data_hub.alunofinancas'),
        ),
        migrations.AlterField(
            model_name='responsaveleducativo',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='func_id',
            field=models.ForeignKey(blank=True, db_column='func_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario'),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
    ]
