# Generated by Django 5.1.6 on 2025-03-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunosaida',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='responsavel_educativo_id',
            field=models.ForeignKey(db_column='responsavel_educativo_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo'),
        ),
        migrations.AlterField(
            model_name='responsaveleducativo',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='responsavel_educativo_id',
            field=models.ForeignKey(db_column='responsavel_educativo_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo'),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
    ]
