# Generated by Django 5.1.6 on 2025-04-09 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinacao',
            name='data_vacina',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
