# Generated by Django 6.0.3 on 2026-03-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensalidadealuno',
            name='ano_letivo',
        ),
        migrations.RemoveField(
            model_name='mensalidadealuno',
            name='periodo_fim',
        ),
        migrations.RemoveField(
            model_name='mensalidadealuno',
            name='periodo_inicio',
        ),
        migrations.AddField(
            model_name='mensalidadealuno',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensalidadealuno',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
