# Generated by Django 5.1.6 on 2025-05-14 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoImagem',
            fields=[
                ('tipo_imagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_imagem', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'tipo_imagem',
            },
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('imagem_id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.TextField()),
                ('alt', models.CharField(default='', max_length=100)),
                ('tipo_imagem_id', models.ForeignKey(db_column='tipo_imagem_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.tipoimagem')),
            ],
            options={
                'db_table': 'imagem',
            },
        ),
    ]
