# Generated by Django 5.1.6 on 2025-02-21 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('despesa_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('categoria', models.CharField(default='', max_length=250)),
                ('valor', models.FloatField(default='')),
                ('descricao', models.CharField(default='', max_length=250)),
                ('data', models.DateField(default='')),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='codigo_postal',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='aluno',
            name='concelho',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cuidados_especias',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_admissao',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_ultima_renovacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_validade',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='aluno',
            name='documento',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escolaridade_anterior',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='fregesia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='morada',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='aluno',
            name='motivo_admissao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='nif',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='niss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='numero_documento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='apelido',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_proprio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='processo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Aluno_saida',
            fields=[
                ('saida_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_saida', models.DateTimeField(blank=True, null=True)),
                ('autorizacao_sair', models.CharField(blank=True, max_length=250, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=100, null=True)),
                ('aluno_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'aluno_saida',
            },
        ),
        migrations.CreateModel(
            name='Responsavel_educativo',
            fields=[
                ('respon_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=250)),
                ('data_nascimento', models.DateField(default='')),
                ('documento', models.CharField(default='', max_length=150)),
                ('numero_documento', models.IntegerField(default='')),
                ('data_validade', models.DateField(default='')),
                ('niss', models.IntegerField(blank=True, null=True)),
                ('nif', models.IntegerField(blank=True, null=True)),
                ('morada', models.CharField(default='', max_length=250)),
                ('codigo_postal', models.CharField(default='', max_length=100)),
                ('concelho', models.CharField(default='', max_length=150)),
                ('fregesia', models.CharField(default='', max_length=150)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('profissao', models.CharField(blank=True, max_length=150, null=True)),
                ('morada_emprego', models.CharField(blank=True, max_length=150, null=True)),
                ('horario_trabalho', models.TimeField(blank=True, null=True)),
                ('aluno_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'responsavel_educativo',
            },
        ),
        migrations.CreateModel(
            name='Filiacao',
            fields=[
                ('filiacao_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('filiacao_responsavel', models.CharField(default='', max_length=100)),
                ('aluno_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
                ('respon_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsavel_educativo')),
            ],
            options={
                'db_table': 'filiacao',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('salario_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('valor', models.FloatField(default='')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('subsidio_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('subsidio_valor', models.FloatField(blank=True, null=True)),
                ('funcionario_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsavel_educativo')),
            ],
            options={
                'db_table': 'salario',
            },
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('vac_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('vacina_name', models.CharField(default='', max_length=250)),
                ('data_vacina', models.DateField(blank=True, null=True)),
                ('plano_vacina', models.BooleanField(blank=True, default=False, null=True)),
                ('aluno_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno')),
            ],
            options={
                'db_table': 'vacinacao',
            },
        ),
    ]
