# Generated by Django 5.1.6 on 2025-03-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filiacao',
            old_name='respon_id',
            new_name='responsavel_educativo_id',
        ),
        migrations.RenameField(
            model_name='salario',
            old_name='funcionario_id',
            new_name='responsavel_educativo_id',
        ),
    ]
