# Generated by Django 5.0.4 on 2026-05-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesafixa',
            name='fornecedor',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='despesafixa',
            name='notas',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='despesasvariavel',
            name='fornecedor',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='despesasvariavel',
            name='notas',
            field=models.CharField(default='', max_length=250),
        ),
    ]
