# Generated by Django 5.1.6 on 2025-04-05 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_alter_alunosaida_aluno_id_alter_filiacao_aluno_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoFinacasCalc',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=255)),
                ('local', models.CharField(blank=True, max_length=255, null=True)),
                ('valencia', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'aluno_finacas_calc',
            },
        ),
        migrations.CreateModel(
            name='AlunoFinancas',
            fields=[
                ('aluno_financas_id', models.AutoField(primary_key=True, serialize=False)),
                ('ano_letivo', models.CharField(default='', max_length=255)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('agregado', models.IntegerField()),
                ('rendim_líquido', models.IntegerField()),
                ('despesa_anual', models.IntegerField()),
                ('irs', models.CharField(default='', max_length=255)),
                ('tax_soc', models.CharField(default='', max_length=255)),
                ('tax_impos', models.CharField(blank=True, max_length=255, null=True)),
                ('renda', models.IntegerField(blank=True, null=True)),
                ('med_transp', models.CharField(blank=True, max_length=255, null=True)),
                ('medicacao', models.CharField(blank=True, max_length=255, null=True)),
                ('outros', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'aluno_financas',
            },
        ),
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('despesa_fixa_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(default='', max_length=250)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('fatura', models.IntegerField()),
                ('pagamento', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'despesa_fixa',
            },
        ),
        migrations.CreateModel(
            name='DespesasVariavel',
            fields=[
                ('despesas_variavel_id', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(default='', max_length=250)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('fatura', models.IntegerField()),
                ('pagamento', models.CharField(default='', max_length=250)),
            ],
            options={
                'db_table': 'despesas_variavel',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_proprio', models.CharField(default='', max_length=100)),
                ('apelido', models.CharField(default='', max_length=100)),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('tipo_documento_identificacao', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_documento_identificacao', models.CharField(default='', max_length=50)),
                ('data_validade', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('niss', models.IntegerField()),
                ('nif', models.IntegerField()),
                ('morada', models.CharField(default='', max_length=255)),
                ('codigo_postal', models.CharField(default='', max_length=255)),
                ('concelho', models.CharField(blank=True, max_length=255, null=True)),
                ('freguesia_residencia', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto_telefonico', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(default='', max_length=255)),
                ('escalao_profissional', models.CharField(blank=True, max_length=255, null=True)),
                ('ativo', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='LinkFiliacao',
            fields=[
                ('type', models.CharField(default='', max_length=100)),
                ('encarr_educacao', models.BooleanField(blank=True, default=False, null=True)),
                ('link_filiacao_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'link_filiacao',
            },
        ),
        migrations.CreateModel(
            name='MensalidadeAluno',
            fields=[
                ('ma_id', models.AutoField(primary_key=True, serialize=False)),
                ('periodo_inicio', models.DateField(default=django.utils.timezone.now)),
                ('periodo_fim', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('mensalidade_calc', models.IntegerField(blank=True, null=True)),
                ('mensalidade_retific', models.IntegerField(blank=True, null=True)),
                ('mensalidade_paga', models.IntegerField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('modo_pagamento', models.CharField(blank=True, max_length=255, null=True)),
                ('acordo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mensalidade_aluno',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('sala_nome', models.CharField(default='', max_length=255)),
                ('sala_local', models.CharField(blank=True, max_length=255, null=True)),
                ('sala_valencia', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.RemoveField(
            model_name='alunosaida',
            name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='responsavel_educativo_id',
        ),
        migrations.AddField(
            model_name='aluno',
            name='archive_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_admissao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_ultima_renovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_validade',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='salario',
            name='subsidio_tipo',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='salario',
            name='subsidio_valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alunosaida',
            name='valencia',
            field=models.ForeignKey(db_column='valencia', default=1, on_delete=django.db.models.deletion.CASCADE, to='data_hub.alunofinacascalc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alunofinancas',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.ForeignKey(blank=True, db_column='salario', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.salario'),
        ),
        migrations.AddField(
            model_name='alunofinacascalc',
            name='func_id',
            field=models.ForeignKey(blank=True, db_column='func_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario'),
        ),
        migrations.AddField(
            model_name='linkfiliacao',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AddField(
            model_name='linkfiliacao',
            name='responsavel_educativo_id',
            field=models.ForeignKey(db_column='responsavel_educativo_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo'),
        ),
        migrations.AddField(
            model_name='mensalidadealuno',
            name='aluno_id',
            field=models.ForeignKey(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AddField(
            model_name='mensalidadealuno',
            name='ano_letivo',
            field=models.ForeignKey(db_column='ano_letivo', on_delete=django.db.models.deletion.CASCADE, to='data_hub.alunofinancas'),
        ),
        migrations.AddField(
            model_name='sala',
            name='funcionario_id',
            field=models.ForeignKey(blank=True, db_column='funcionario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='sala_id',
            field=models.ForeignKey(db_column='sala_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='data_hub.sala'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Filiacao',
        ),
    ]
