# Generated by Django 6.0.3 on 2026-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_remove_mensalidadealuno_ano_letivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configipss',
            name='active_flag',
            field=models.BooleanField(default=True),
        ),
    ]
