# Generated by Django 5.1.6 on 2025-02-21 09:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_despesa_aluno_codigo_postal_aluno_concelho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_admissao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_ultima_renovacao',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_validade',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='aluno_saida',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='aluno_saida',
            name='saida_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='despesa_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='filiacao_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filiacao',
            name='respon_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsavel_educativo'),
        ),
        migrations.AlterField(
            model_name='responsavel_educativo',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='responsavel_educativo',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='responsavel_educativo',
            name='data_validade',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='responsavel_educativo',
            name='numero_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='responsavel_educativo',
            name='respon_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salario',
            name='data_pagamento',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='salario',
            name='funcionario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsavel_educativo'),
        ),
        migrations.AlterField(
            model_name='salario',
            name='salario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salario',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='aluno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='data_vacina',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='vacinacao',
            name='vac_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
