# Generated by Django 5.1.6 on 2025-03-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0002_alter_aluno_sala_id_alter_alunofinacascalc_func_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkfiliacao',
            name='aluno_id',
            field=models.OneToOneField(db_column='aluno_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.aluno'),
        ),
        migrations.AlterField(
            model_name='linkfiliacao',
            name='re_id',
            field=models.OneToOneField(db_column='re_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.responsaveleducativo'),
        ),
    ]
