# Generated by Django 5.1.6 on 2025-04-05 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_alunofinacascalc_alunofinancas_despesafixa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunofinacascalc',
            name='func_id',
        ),
        migrations.AddField(
            model_name='alunofinacascalc',
            name='funcionario_id',
            field=models.ForeignKey(blank=True, db_column='funcionario_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_hub.funcionario'),
        ),
    ]
