# Generated by Django 5.1.6 on 2025-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0003_alter_imagem_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='tipo_imagem_id',
        ),
        migrations.AddField(
            model_name='imagem',
            name='tipo_imagem_id',
            field=models.ManyToManyField(db_table='imagem_tipo_imagem', to='data_hub.tipoimagem'),
        ),
    ]
