# Generated by Django 5.1.6 on 2025-05-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0004_remove_imagem_tipo_imagem_id_imagem_tipo_imagem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('tipo_problema_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_problema', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'tipo_problema',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cuidados_especias',
        ),
        migrations.CreateModel(
            name='CuidadoEspecial',
            fields=[
                ('cuidado_especial_id', models.AutoField(primary_key=True, serialize=False)),
                ('problema', models.CharField(default='', max_length=255)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('tipo_problema', models.ForeignKey(db_column='tipo_problema_id', on_delete=django.db.models.deletion.CASCADE, to='data_hub.tipoproblema')),
            ],
            options={
                'db_table': 'cuidados_especiais',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='cuidados_especias',
            field=models.ManyToManyField(db_table='aluno_cuidados_especiais', to='data_hub.cuidadoespecial'),
        ),
    ]
