# Generated by Django 5.1.6 on 2025-04-05 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0004_remove_alunofinacascalc_func_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidadealuno',
            old_name='ma_id',
            new_name='mensalidade_aluno_id',
        ),
    ]
