# Generated by Django 5.1.6 on 2025-05-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0005_tipoproblema_remove_aluno_cuidados_especias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidadoespecial',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
