# Generated by Django 5.1.6 on 2025-05-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_hub', '0006_alter_cuidadoespecial_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidadoespecial',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
